### PR TITLE
Add program image to schedule

### PR DESCRIPTION
**Pull request by adammichalowski-tomtom**

### CODE REVIEW

**Comment by xivk** [comment]
Probably we need to remove this:

image

**Comment by xivk** [comment]
And remove title

**Comment by adammichalowski-tomtom** [comment]
Uploaded uncompressed image which is resized to 2560px width (2x max width of the page container for retina screens).

**Review by jbelien — DISMISSED** [review]
Thanks @adammichalowski-tomtom !

But we need to provide a responsive solution (see #114)
This is currently the view on a phone:

Capture d’écran 2023-10-03 à 16 32 42 --

**Comment by adammichalowski-tomtom** [comment]
> Thanks @adammichalowski-tomtom !
> 
> But we need to provide a responsive solution (see #114) This is currently the view on a phone:
> 
> Capture d’écran 2023-10-03 à 16 32 42 --

You can zoom in the table with your fingers.

**Comment by xivk** [comment]
@jbelien we will publish like this and then update to an approach where each talk has its own page and the program is not an image but an actual properly coded page. But we need to be fast and publish tomorrow

**Comment by jbelien** [comment]
> @jbelien we will publish like this and then update to an approach where each talk has its own page and the program is not an image but an actual properly coded page. But we need to be fast and publish tomorrow

All good for me! 👍 
That's why I've remove my change request so you could merge it.

**Pull request merged**
