### PR TITLE
Map submission

### PR DESCRIPTION
**Pull request by nobohan**
Hello, 

This is a PR for adding a new page "Call for maps" to the website, based on the "Call for presentation" page. 

New button on the home page:

image

New page:

image

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
As you see in the checks, it doesn't build!
Please make the necessary changes.

**Comment by marjanvandekauter-tomtom** [comment]
@nobohan can you please update the pull request and use the reviewed version of the call that I sent you from the SotM-EU email address? Also, please use the button text "Submit your maps".

@jbelien please hold off on merging this request until the content has been updated by Julien.

Thanks both!

**Comment by nobohan** [comment]
@marjanvandekauter-tomtom Sorry Marjan, I had forgotten to add your changes! This is done now. 

@jbelien I also corrected 2 things and I guess it is passing the tests now.

**Comment by marjanvandekauter-tomtom** [comment]
The content looks good now.

**Review by jbelien — CHANGES_REQUESTED** [review]
The header looks strange now that there are 2 buttons.
Could you improve the layout a bit ?

Capture d’écran 2023-09-25 à 15 40 54

Please also add the "Submit your maps" link under "Get your tickets" in the mobile menu.

Capture d’écran 2023-09-25 à 15 40 58

Thanks.

**Review by jbelien — CHANGES_REQUESTED** [review]
Also, don't forget to run Prettier!

**Comment by nobohan** [comment]
For mobile, I moved the "submit your maps" button to the bottom of the page just before the sponsors, and add it in the mobile hamburger menu. 

image

image

**Comment by marjanvandekauter-tomtom** [comment]
Looking at the time, I think we might have to change the "Call for maps open" date in the Deadline section to September 26?

**Comment by marjanvandekauter-tomtom** [comment]
@jbelien have the requested changes been made and can the merging process continue?

**Comment by jbelien** [comment]
> Looking at the time, I think we might have to change the "Call for maps open" date in the Deadline section to September 26?

Updated in 31fdd6295a15e1b25a61d7273f65124727addb26

> @jbelien have the requested changes been made and can the merging process continue (after changing the call date--see comment above)?

I've made the necessary changes. I'll merge in a few minutes.

**Review by jbelien — APPROVED** [review]

**Pull request merged**
